# Generated by Django 4.1.3 on 2022-11-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("language", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Surah",
            fields=[
                (
                    "surah_number",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="surah_number",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bismillah_verse_time_in_arabic", models.CharField(max_length=100)),
                ("bismillah_verse_time_out_arabic", models.CharField(max_length=100)),
                ("bismillah_verse_time_in_translation", models.CharField(max_length=100)),
                ("bismillah_verse_time_out_translation", models.CharField(max_length=100)),
                ("bismillah_text_arabic", models.TextField()),
                ("bismillah_text_translation", models.TextField()),
                ("full_verse_time_in_arabic", models.CharField(max_length=100)),
                ("full_verse_time_out_arabic", models.CharField(max_length=100)),
                ("full_verse_time_in_translation", models.CharField(max_length=100)),
                ("full_verse_time_out_translation", models.CharField(max_length=100)),
                ("full_verse_text_arabic", models.TextField()),
                ("full_verse_text_translation", models.TextField()),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.language",
                    ),
                ),
            ],
        ),
    ]
