# Generated by Django 4.1.3 on 2022-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surah",
            name="surah_number",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
