# Generated by Django 4.1.3 on 2022-11-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0002_alter_surah_surah_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_in_arabic",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_in_translation",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_out_arabic",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_out_translation",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_in_arabic",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_in_translation",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_out_arabic",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_out_translation",
            field=models.TimeField(),
        ),
    ]
