# Generated by Django 4.1.3 on 2022-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0003_alter_surah_bismillah_verse_time_in_arabic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_in_arabic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_in_translation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_out_arabic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="bismillah_verse_time_out_translation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_in_arabic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_in_translation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_out_arabic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="surah",
            name="full_verse_time_out_translation",
            field=models.CharField(max_length=100),
        ),
    ]
