# Generated by Django 4.1.3 on 2022-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0004_alter_surah_bismillah_verse_time_in_arabic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surah",
            name="audio",
            field=models.FileField(default=1, upload_to="media/audio/"),
            preserve_default=False,
        ),
    ]
