# Generated by Django 4.1.3 on 2022-11-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0005_surah_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surah",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="bismillah_text_arabic",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="bismillah_text_translation",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="bismillah_verse_time_in_arabic",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="bismillah_verse_time_in_translation",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="bismillah_verse_time_out_arabic",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="bismillah_verse_time_out_translation",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="full_verse_text_arabic",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="full_verse_text_translation",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="full_verse_time_in_arabic",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="full_verse_time_in_translation",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="full_verse_time_out_arabic",
        ),
        migrations.RemoveField(
            model_name="surah",
            name="full_verse_time_out_translation",
        ),
    ]
