# Generated by Django 4.1.3 on 2022-11-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0006_remove_surah_audio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surah",
            name="language",
        ),
    ]
