# Generated by Django 4.1.3 on 2022-11-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0001_initial"),
        ("surah", "0007_remove_surah_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurahDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verse", models.CharField(max_length=10)),
                ("time_in", models.CharField(max_length=50)),
                ("time_out", models.CharField(max_length=50)),
                ("text", models.TextField()),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.language",
                    ),
                ),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surah.surah"
                    ),
                ),
            ],
        ),
    ]
