# Generated by Django 4.1.3 on 2022-11-09 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0009_surahdetail_audio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="media/audio/")),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surah.surah"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="surahdetail",
            name="audio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surah.audio"
            ),
        ),
    ]
