# Generated by Django 4.1.3 on 2022-11-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0010_audio_alter_surahdetail_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surahdetail",
            name="audio",
        ),
    ]
