# Generated by Django 4.1.3 on 2022-11-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0011_remove_surahdetail_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="surahdetail",
            name="audio",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="surah.audio"
            ),
            preserve_default=False,
        ),
    ]
