# Generated by Django 4.1.3 on 2022-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0012_surahdetail_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surahdetail",
            name="audio",
        ),
        migrations.AddField(
            model_name="surah",
            name="audio",
            field=models.FileField(default=1, upload_to="media/audio/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Audio",
        ),
    ]
