# Generated by Django 4.1.3 on 2022-11-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0001_initial"),
        ("surah", "0013_remove_surahdetail_audio_surah_audio_delete_audio"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurahDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.CharField(max_length=100)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.language",
                    ),
                ),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surah.surah"
                    ),
                ),
            ],
        ),
    ]
