# Generated by Django 4.1.3 on 2022-11-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0015_alter_surah_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surah",
            name="audio",
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/")),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surah.surah"
                    ),
                ),
            ],
        ),
    ]
