# Generated by Django 4.1.3 on 2022-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surah", "0018_alter_audio_language_alter_audio_surah"),
    ]

    operations = [
        migrations.AddField(
            model_name="surahdetail",
            name="verse_serial",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
